name: GitHub Actions TEST
on: 
  pull_request:
    branches:
      - test


jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest

    env:
      TF_VAR_PROJ_ENV: ${{ github.base_ref }}
      TF_lOG: "INFO"

    permissions:
      # so GitHub can check out this repo using the default github.token
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"
              
      - run: terraform init
              
      - id: plan
        run: terraform plan -no-color
              
      - run: echo $TF_VAR_PROJ_ENV
      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}
    
